#!/usr/bin/env python3
"""Emit pgfplots/TikZ sources for the block-length mechanism panels.

Three figures, the TikZ counterparts of the matplotlib panels in
``scripts/plot_blocklen_png.py``:

  fig1a  block-length distribution -- share of blocks at each length L,
         against the fair-coin reference 2^-L
  fig2a  alternating stretches -- how many maximal streaks of k consecutive
         length-1 blocks the network holds
  fig4a  the identity -- per-layer sign-transition density (predicted) against
         the measured bit errors per misread cell, with the y=x line

Each figure writes

  * ``<name>.dat``            -- the numbers, one column per series
  * ``<name>_body.tex``       -- the figure body, to ``\\input`` into the paper
  * ``<name>.tex``            -- a standalone wrapper to compile on its own

plus a ``README.md`` recording what backs each series. Colours are one
``\\definecolor`` per series at the top of each body file, so re-colouring a
series is a single edit and never needs a regeneration.

Usage::

    python scripts/plot_blocklen_tikz.py
    python scripts/plot_blocklen_tikz.py --only cat1_baseline cat5_regularizer
    python scripts/plot_blocklen_tikz.py --color cat1_baseline=008300 \\
        --color cat5_regularizer=EB6834/EDA100   # two-tone alternating line

Stdlib only -- no matplotlib, no torch, runs on the Mac mount.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

_SCRIPTS_DIR = Path(__file__).resolve().parent
if str(_SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(_SCRIPTS_DIR))

# plot_blocklen_png keeps matplotlib inside the figure functions, so importing it
# here stays stdlib-only and the two emitters cannot drift apart on the data.
from plot_blocklen_png import (  # noqa: E402
    DEFAULT_RUNS, PRETTY, collect, structure_arms,
)

REPO_ROOT = _SCRIPTS_DIR.parent
DEFAULT_OUT = REPO_ROOT / "docs" / "figures" / "blocklen-tikz"
DEFAULT_ARMS = ["cat1_baseline", "cat5_regularizer"]
#: Overridden per invocation with --color; these are the paper's two hues.
DEFAULT_COLORS = {
    "cat1_baseline": "008300",
    # A two-hex value draws the line in the first tone with the second dashed
    # over it, so the colours alternate along it.
    "cat5_regularizer": ("EB6834", "EDA100"),
}
#: Shape as well as colour, so the series survive greyscale printing.
MARKS = ["*", "square*", "triangle*", "diamond*"]
GREY = "8A8985"

BODY_NOTE = r"""% Generated by scripts/plot_blocklen_tikz.py -- regenerating overwrites this file.
% Figure body only (no \documentclass). Two ways to use it:
%   1. compile the sibling standalone wrapper, or
%   2. \input{} this file inside a figure environment in the paper -- the paper
%      preamble then needs: \usepackage{pgfplots} \pgfplotsset{compat=1.18}
%      and, if the .dat files are not beside the main .tex,
%      \pgfplotsset{table/search path={<dir holding the .dat files>}}
"""

WRAPPER = r"""% Generated by scripts/plot_blocklen_tikz.py -- regenerating overwrites this file.
% Standalone wrapper; all the figure content lives in the _body.tex it inputs.
\documentclass[tikz, border=2pt]{standalone}
\usepackage{pgfplots}
\pgfplotsset{compat=1.18}
\begin{document}
\input{@@BODY@@}
\end{document}
"""


def color_macro(cat: str) -> str:
    """``cat5_regularizer`` -> ``ndCat5`` -- the repo's existing macro spelling."""
    m = re.match(r"(cat\d+)", cat)
    stem = m.group(1) if m else re.sub(r"[^A-Za-z0-9]+", "", cat)
    return "nd" + stem[:1].upper() + stem[1:]


def tex_escape(s: str) -> str:
    return (s.replace("\\", r"\textbackslash{}").replace("_", r"\_")
             .replace("&", r"\&").replace("%", r"\%").replace("#", r"\#"))


def hexes(colors, cat) -> list[str]:
    """One hex, or two for a series drawn as an alternating two-tone line."""
    v = colors[cat]
    return list(v) if isinstance(v, (list, tuple)) else [v]


def two_tone(colors, cat) -> bool:
    return len(hexes(colors, cat)) > 1


def dash_defs(arms, colors, on="3.6pt", off="3.6pt") -> str:
    """The dash knobs, or nothing when no series needs them."""
    if not any(two_tone(colors, c) for c in arms):
        return ""
    return DASH_DEFS.replace("@@ON@@", on).replace("@@OFF@@", off)


def color_defs(arms, colors) -> str:
    names = []
    for c in arms:
        names.append((color_macro(c), hexes(colors, c)[0], PRETTY.get(c, c)))
        if two_tone(colors, c):
            names.append((color_macro(c) + "Alt", hexes(colors, c)[1],
                          f"{PRETTY.get(c, c)}, alternating tone"))
    names.append(("ndRef", GREY, "fair-coin / identity reference"))
    width = max(len(n) for n, _, _ in names)
    return "\n".join(f"\\definecolor{{{n}}}{{HTML}}{{{h.upper()}}}"
                     f"{' ' * (width - len(n))}  % {note}" for n, h, note in names)


#: Dash rhythm of a two-tone line, as knobs so it can be retuned without a
#: regeneration. The solid tone shows through the gaps of the dashed one.
DASH_DEFS = r"""
%% Dash rhythm of the two-tone series: the second colour is dashed ON TOP of
%% the first, so these two lengths set how the colours alternate.
\def\DashOn{@@ON@@}
\def\DashOff{@@OFF@@}
"""


def line_series(cat, i, colors, xcol, ycol, dat, indent="    ") -> list[str]:
    """``\\addplot`` lines plus an explicit legend key for one line series.

    A two-tone series is one line drawn twice -- solid in the first colour, then
    dashed in the second on top -- so the colours alternate along it. Both are
    ``forget plot`` and the key is built by hand, because pgfplots would
    otherwise put two entries in the legend for what is one series.
    """
    cm, mk = color_macro(cat), MARKS[i % len(MARKS)]
    mark_opts = (f"mark={mk}, mark size=1.3pt,"
                 f" mark options={{solid, fill={cm}, draw={cm}}}")
    out = []
    if two_tone(colors, cat):
        cm2 = cm + "Alt"
        out.append(f"{indent}%% two-tone: solid {cm} with {cm2} dashed over it")
        out.append(f"{indent}\\addplot[{cm}, line width=1.1pt, {mark_opts}, forget plot]"
                   f" table[x={xcol}, y={ycol}] {{{dat}}};")
        out.append(f"{indent}\\addplot[{cm2}, line width=1.1pt, mark=none,"
                   f" dash pattern=on \\DashOn off \\DashOff, forget plot]"
                   f" table[x={xcol}, y={ycol}] {{{dat}}};")
        out.append(f"{indent}\\addlegendimage{{legend image code/.code={{%")
        out.append(f"{indent}  \\draw[{cm}, line width=1.1pt] (0cm,0cm) -- (0.6cm,0cm);")
        out.append(f"{indent}  \\draw[{cm2}, line width=1.1pt,"
                   f" dash pattern=on \\DashOn off \\DashOff] (0cm,0cm) -- (0.6cm,0cm);")
        out.append(f"{indent}  \\draw[{cm}, {mark_opts}] plot coordinates {{(0.3cm,0cm)}};")
        out.append(f"{indent}}}}}")
    else:
        out.append(f"{indent}\\addplot[{cm}, line width=1.1pt, {mark_opts}, forget plot]"
                   f" table[x={xcol}, y={ycol}] {{{dat}}};")
        out.append(f"{indent}\\addlegendimage{{{cm}, line width=1.1pt, {mark_opts}}}")
    out.append(f"{indent}\\addlegendentry{{{tex_escape(PRETTY.get(cat, cat))}}}")
    return out


def ref_series(dat, xcol, ycol, label="random signs", indent="    ") -> list[str]:
    """The dashed grey reference, with a key built the same explicit way."""
    return [
        f"{indent}\\addplot[ndRef, line width=0.9pt, dashed, forget plot]"
        f" table[x={xcol}, y={ycol}] {{{dat}}};",
        f"{indent}\\addlegendimage{{ndRef, line width=0.9pt, dashed}}",
        f"{indent}\\addlegendentry{{{label}}}",
    ]


def fmt(v) -> str:
    """``nan`` for a missing point -- pgfplots skips it under unbounded coords=jump."""
    if v is None:
        return "nan"
    return f"{v:.6g}" if isinstance(v, float) else str(v)


def write_dat(path: Path, header: list[str], rows: list[list]) -> None:
    lines = [" ".join(header)]
    lines += [" ".join(fmt(v) for v in row) for row in rows]
    path.write_text("\n".join(lines) + "\n")


def write_figure(out: Path, name: str, body: str, libs: str = "") -> list[Path]:
    body_path = out / f"{name}_body.tex"
    note = BODY_NOTE
    if libs:
        note += f"%      \\usepgfplotslibrary{{{libs}}}\n"
    body_path.write_text(note + body)
    wrapper = out / f"{name}.tex"
    text = WRAPPER.replace("@@BODY@@", body_path.name)
    if libs:
        text = text.replace("\\pgfplotsset{compat=1.18}",
                            f"\\pgfplotsset{{compat=1.18}}\n\\usepgfplotslibrary{{{libs}}}")
    wrapper.write_text(text)
    return [body_path, wrapper]


# --------------------------------------------------------------------------
# fig1a -- block-length distribution
# --------------------------------------------------------------------------
FIG1A = r"""
%% Figure size and the plotted range of L. The .dat file holds every length
%% that occurs, so cropping here needs a recompile only, never a regeneration.
\def\FigWidth{@@W@@}
\def\FigHeight{@@H@@}
\def\LMax{@@LMAX@@}
@@DASHDEFS@@

\begin{tikzpicture}
@@COLORS@@

  \begin{axis}[
      width=\FigWidth, height=\FigHeight,
      xlabel={block length $L$ (cells of equal sign)},
      ylabel={@@YLABEL@@},
      ymode=log,
      xmin=0, xmax=\LMax, ymin=@@YMIN@@,
      unbounded coords=jump,
      grid=both,
      major grid style={line width=0.3pt, draw=black!12},
      minor grid style={line width=0.2pt, draw=black!6},
      tick align=outside, tick pos=left,
      axis line style={draw=black!35},
      legend cell align={left},
      legend style={draw=black!20, fill=white, fill opacity=0.9,
                    text opacity=1, font=\small, at={(0.98,0.98)},
                    anchor=north east},
    ]
@@PLOTS@@
  \end{axis}
\end{tikzpicture}
"""


#: The two y-axes fig1a can carry. ``share`` normalises by each arm's OWN block
#: count, so it compares distribution SHAPE. ``count`` has a denominator the arms
#: genuinely share -- both store the same number of cells -- so sum(L * count) is
#: equal across arms and the plot conserves mass: it shows cells moving out of
#: short blocks and into long ones, which normalising away by block count hides.
FIG1A_VIEWS = {
    "share": ("fig1a_blocklen_distribution", "share of all blocks"),
    "count": ("fig1a_blocklen_counts", "number of blocks"),
}


def build_fig1a(out: Path, bundle, arms, colors, views) -> tuple[list[Path], int, dict]:
    data = bundle["data"]
    hists = {c: data[c]["structure"]["run_hist"] for c in arms}
    totals = {c: sum(h.values()) for c, h in hists.items()}
    cells = {c: sum(L * n for L, n in hists[c].items()) for c in arms}
    lmax = max(max((L for L, n in h.items() if n >= 5), default=1) for h in hists.values())
    # The count view's reference needs a block total to scale 2^-L by, and the
    # arms do not share one. The baseline's is the meaningful choice: it IS the
    # random-sign arm, so the dashed line is "what the baseline would hold".
    ref_total = totals[arms[0]]

    n_arms = len(arms)
    written = []
    for view in views:
        # Each view writes its OWN <name>.dat holding only the columns it plots.
        # A shared table would be smaller, but then `fig1a_blocklen_counts.tex`
        # would read a file named after the other figure -- and copying one
        # figure's files into a paper would silently leave its table behind.
        name, ylabel = FIG1A_VIEWS[view]
        dat = f"{name}.dat"
        header = ["L"] + [color_macro(c) for c in arms] + ["faircoin"]
        rows = []
        for L in range(1, lmax + 1):
            counts = [hists[c].get(L, 0) for c in arms]
            row = [L]
            if view == "share":
                row += [(n / totals[c] if n else None) for c, n in zip(arms, counts)]
                row.append(0.5 ** L)
            else:
                row += [(n if n else None) for n in counts]
                row.append(ref_total * 0.5 ** L)
            rows.append(row)
        write_dat(out / dat, header, rows)

        # Floor from the plotted series only: the fair-coin reference runs below
        # the data and would drag the axis down a spare decade. pgfplots clips it.
        vals = [v for row in rows for v in row[1:1 + n_arms] if v is not None]
        ymin = min(vals) / 3

        plots = []
        for i, c in enumerate(arms):
            plots.append(f"    %% ---- {c}"
                         f" ({cells[c]:,} cells in {totals[c]:,} blocks) ----".replace(",", "\\,"))
            plots += line_series(c, i, colors, "L", color_macro(c), dat)
        plots.append("    %% ---- fair coin: a random sign sequence gives 2^-L"
                     + (" ----" if view == "share"
                        else f", here scaled by the baseline's {totals[arms[0]]:,} blocks ----".replace(",", "\\,")))
        plots += ref_series(dat, "L", "faircoin")

        body = (FIG1A.replace("@@COLORS@@", "  " + color_defs(arms, colors).replace("\n", "\n  "))
                .replace("@@PLOTS@@", "\n".join(plots))
                .replace("@@YLABEL@@", ylabel)
                .replace("@@DASHDEFS@@", dash_defs(arms, colors))
                .replace("@@LMAX@@", str(lmax + 1))
                .replace("@@YMIN@@", f"{ymin:.3g}")
                .replace("@@W@@", "8.6cm").replace("@@H@@", "6.2cm"))
        written += write_figure(out, name, body)
    return written, lmax, {"totals": totals, "cells": cells}


# --------------------------------------------------------------------------
# fig1a + fig2a side by side
# --------------------------------------------------------------------------
PAIR = r"""
%% ======================================================================
%%  Panel geometry. `scale only axis` makes these the size of the AXIS BOX,
%%  not of the box plus its ticks and labels -- which is what keeps the two
%%  panels exactly equal however wide their tick labels turn out to be.
%%  Change these two lengths and both panels follow.
%% ======================================================================
\def\PanelWidth{@@W@@}
\def\PanelHeight{@@H@@}
\def\PanelSep{@@SEP@@}

%% Panel titles.
\def\TitleLeft{@@TL@@}
\def\TitleRight{@@TR@@}

%% Plotted ranges.
\def\LMax{@@LMAX@@}
\def\KMax{@@KMAX@@}
@@DASHDEFS@@

\begin{tikzpicture}
@@COLORS@@

  \begin{groupplot}[
      group style={group size=2 by 1, horizontal sep=\PanelSep},
      width=\PanelWidth, height=\PanelHeight,
      scale only axis,
      ymode=log,
      unbounded coords=jump,
      grid=both,
      major grid style={line width=0.3pt, draw=black!12},
      minor grid style={line width=0.2pt, draw=black!6},
      tick align=outside, tick pos=left,
      axis line style={draw=black!35},
      title style={at={(0,1)}, anchor=south west, yshift=1.5pt,
                   font=\small\bfseries, align=left},
      legend cell align={left},
      legend style={draw=black!20, fill=white, fill opacity=0.9,
                    text opacity=1, font=\footnotesize},
    ]

  %% ---------------- left: block lengths ----------------
  \nextgroupplot[
      title={\TitleLeft},
      xlabel={block length $L$ (cells of equal sign)},
      ylabel={@@YLABEL@@},
      xmin=0, xmax=\LMax, ymin=@@YMINL@@,
      legend pos=north east,
    ]
@@PLOTSL@@

  %% ---------------- right: alternating stretches ----------------
  %% Its own legend, so the panel stands on its own if it is cropped out or
  %% reused alone. It omits the fair-coin key, which this panel does not draw.
  \nextgroupplot[
      title={\TitleRight},
      xlabel={length of the alternating stretch (cells)},
      ylabel={number of stretches},
      xmin=1, xmax=\KMax, ymin=@@YMINR@@,
      legend pos=north east,
    ]
@@PLOTSR@@

  \end{groupplot}
\end{tikzpicture}
"""


def build_pair(out: Path, bundle, arms, colors, view) -> tuple[list[Path], str]:
    """fig1a (left) and fig2a (right) as one group plot with equal panels."""
    data = bundle["data"]
    runs = {c: data[c]["structure"]["run_hist"] for c in arms}
    alts = {c: data[c]["structure"]["alt_hist"] for c in arms}
    totals = {c: sum(runs[c].values()) for c in arms}
    lmax = max(max((L for L, n in runs[c].items() if n >= 5), default=1) for c in arms)
    kmax = max(max((k for k, n in alts[c].items() if n >= 5), default=2) for c in arms)
    ref_total = totals[arms[0]]

    name = f"fig1a2a_pair_{view}"
    dat = f"{name}.dat"
    # One table, two independent x columns. The two panels have different x
    # ranges, so the shorter columns are padded with nan and pgfplots skips
    # them under `unbounded coords=jump`.
    header = (["L"] + [color_macro(c) + "Blocks" for c in arms] + ["faircoinBlocks"]
              + ["k"] + [color_macro(c) + "Alt" for c in arms] + ["faircoinAlt"])
    rows = []
    for i in range(max(lmax, kmax - 1)):
        L = i + 1
        k = i + 2
        row: list = [L if L <= lmax else None]
        for c in arms:
            n = runs[c].get(L, 0) if L <= lmax else 0
            row.append((n / totals[c] if view == "share" else n) if n else None)
        row.append((0.5 ** L if view == "share" else ref_total * 0.5 ** L)
                   if L <= lmax else None)
        row.append(k if k <= kmax else None)
        for c in arms:
            n = alts[c].get(k, 0) if k <= kmax else 0
            row.append(n if n else None)
        row.append(ref_total * 0.5 ** (k + 2) if k <= kmax else None)
        rows.append(row)
    write_dat(out / dat, header, rows)

    n_arms = len(arms)
    left_vals = [v for r in rows for v in r[1:1 + n_arms] if v is not None]
    right_vals = [v for r in rows for v in r[2 + n_arms + 1:2 + n_arms + 1 + n_arms]
                  if v is not None]

    def series(axis_x, suffix):
        out_lines = []
        for i, c in enumerate(arms):
            out_lines += line_series(c, i, colors, axis_x,
                                     color_macro(c) + suffix, dat)
        return out_lines

    plots_l = series("L", "Blocks")
    plots_l.append("    %% fair coin: a random sign sequence gives 2^-L"
                   + ("" if view == "share"
                      else f", scaled by the baseline's {ref_total:,} blocks".replace(",", "\\,")))
    plots_l += ref_series(dat, "L", "faircoinBlocks")

    plots_r = series("k", "Alt")
    plots_r.append("    %% Same fair-coin law as the left panel, shifted by 1/4. In the"
                   " `faircoinAlt` column; uncomment to show:")
    plots_r.append(f"    %% \\addplot[ndRef, line width=0.9pt, dashed]"
                   f" table[x=k, y=faircoinAlt] {{{dat}}};")

    ylabel = "share of all blocks" if view == "share" else "number of blocks"
    body = (PAIR.replace("@@COLORS@@", "  " + color_defs(arms, colors).replace("\n", "\n  "))
            .replace("@@PLOTSL@@", "\n".join(plots_l))
            .replace("@@PLOTSR@@", "\n".join(plots_r))
            .replace("@@YLABEL@@", ylabel)
            .replace("@@DASHDEFS@@", dash_defs(arms, colors))
            .replace("@@LMAX@@", str(lmax + 1)).replace("@@KMAX@@", str(kmax + 1))
            .replace("@@YMINL@@", f"{min(left_vals) / 3:.3g}")
            .replace("@@YMINR@@", f"{min(right_vals) / 3:.3g}")
            .replace("@@TL@@", "(a) Same-sign blocks")
            .replace("@@TR@@", "(b) Alternating stretches")
            .replace("@@W@@", "6.0cm").replace("@@H@@", "4.6cm")
            .replace("@@SEP@@", "1.6cm"))
    return write_figure(out, name, body, libs="groupplots"), name


# --------------------------------------------------------------------------
# fig2a -- alternating stretches
# --------------------------------------------------------------------------
FIG2A = r"""
%% Figure size and the plotted range of k.
\def\FigWidth{@@W@@}
\def\FigHeight{@@H@@}
\def\KMax{@@KMAX@@}
@@DASHDEFS@@

\begin{tikzpicture}
@@COLORS@@

  \begin{axis}[
      width=\FigWidth, height=\FigHeight,
      xlabel={length of the alternating stretch (cells)},
      ylabel={number of stretches},
      ymode=log,
      xmin=1, xmax=\KMax,
      unbounded coords=jump,
      grid=both,
      major grid style={line width=0.3pt, draw=black!12},
      minor grid style={line width=0.2pt, draw=black!6},
      tick align=outside, tick pos=left,
      axis line style={draw=black!35},
      legend cell align={left},
      legend style={draw=black!20, fill=white, fill opacity=0.9,
                    text opacity=1, font=\small, at={(0.98,0.98)},
                    anchor=north east},
    ]
@@PLOTS@@
  \end{axis}
\end{tikzpicture}
"""


def build_fig2a(out: Path, bundle, arms, colors) -> tuple[list[Path], int]:
    data = bundle["data"]
    hists = {c: data[c]["structure"]["alt_hist"] for c in arms}
    kmax = max(max((k for k, n in h.items() if n >= 5), default=2) for h in hists.values())
    # Same fair-coin law as fig1a, shifted by 1/4 -- the chance the streak is
    # bounded on both sides by a non-singleton block. Emitted so the reference
    # can be switched on, but left out of the plot: fig2a is a count panel.
    n_blocks = sum(data[arms[0]]["structure"]["run_hist"].values())

    header = ["k"] + [color_macro(c) for c in arms] + ["faircoin"]
    rows = []
    for k in range(2, kmax + 1):
        row = [k]
        for c in arms:
            n = hists[c].get(k, 0)
            row.append(n if n else None)
        row.append(n_blocks * 0.5 ** (k + 2))
        rows.append(row)
    write_dat(out / "fig2a_alternating_stretches.dat", header, rows)

    plots = []
    for i, c in enumerate(arms):
        plots.append(f"    %% ---- {c} ----")
        plots += line_series(c, i, colors, "k", color_macro(c),
                             "fig2a_alternating_stretches.dat")
    plots.append("    %% The fair-coin reference is in the .dat as column `faircoin`")
    plots.append("    %% (same geometric law as fig1a, shifted by 1/4). Uncomment to show:")
    plots.append("    %% \\addplot[ndRef, line width=0.9pt, dashed]"
                 " table[x=k, y=faircoin] {fig2a_alternating_stretches.dat};")
    plots.append("    %% \\addlegendentry{random signs}")

    body = (FIG2A.replace("@@COLORS@@", "  " + color_defs(arms, colors).replace("\n", "\n  "))
            .replace("@@PLOTS@@", "\n".join(plots))
            .replace("@@DASHDEFS@@", dash_defs(arms, colors))
            .replace("@@KMAX@@", str(kmax + 1))
            .replace("@@W@@", "8.6cm").replace("@@H@@", "6.2cm"))
    return write_figure(out, "fig2a_alternating_stretches", body), kmax


# --------------------------------------------------------------------------
# fig4a -- the transition-density identity
# --------------------------------------------------------------------------
FIG4A = r"""
%% Figure size and the (shared) axis range. x and y are the same quantity
%% measured two ways, so they must keep the same limits.
\def\FigWidth{@@W@@}
\def\FigHeight{@@H@@}
\def\AxMin{@@MIN@@}
\def\AxMax{@@MAX@@}

\begin{tikzpicture}
@@COLORS@@

  \begin{axis}[
      width=\FigWidth, height=\FigHeight,
      xlabel={predicted: sign-transition density of the stored weights},
      ylabel={measured: bit errors per misread cell},
      xmin=\AxMin, xmax=\AxMax, ymin=\AxMin, ymax=\AxMax,
      axis equal image=false,
      scale only axis,
      grid=both,
      major grid style={line width=0.3pt, draw=black!12},
      minor grid style={line width=0.2pt, draw=black!6},
      tick align=outside, tick pos=left,
      axis line style={draw=black!35},
      legend cell align={left},
      legend style={draw=black!20, fill=white, fill opacity=0.9,
                    text opacity=1, font=\small, at={(0.02,0.98)},
                    anchor=north west},
    ]
    %% y = x: where a measurement that matches the prediction exactly must land.
    \addplot[ndRef, line width=0.9pt, dashed, domain=\AxMin:\AxMax, forget plot] {x};

@@PLOTS@@
  \end{axis}
\end{tikzpicture}
"""


def build_fig4a(out: Path, bundle, arms, colors) -> tuple[list[Path], dict]:
    # A scatter has no line to alternate along, so a two-tone series is drawn in
    # its first tone here; the colour_defs block still names both.
    data = bundle["data"]
    series, stats = {}, {}
    for cat in arms:
        struct, dyn = data[cat]["structure"], data[cat]["dynamic"]
        seeds = sorted(dyn)
        pts = []
        for lname in struct["layer_order"]:
            reads = sum(dyn[s]["wrong_reads_layer"][lname][0] for s in seeds)
            if reads == 0:
                continue
            flips = sum(dyn[s]["bitflips_layer"][lname][0] for s in seeds)
            pts.append((lname, struct["layers"][lname]["transition_density"],
                        flips / reads, reads))
        series[cat] = pts
        gflips = sum(dyn[s]["bitflips"][0] for s in seeds)
        greads = sum(dyn[s]["wrong_reads"][0] for s in seeds)
        stats[cat] = {"predicted": struct["transition_density"],
                      "measured": gflips / greads, "layers": len(pts)}

    vals = [v for pts in series.values() for p in pts for v in p[1:3]]
    vals += [v for st in stats.values() for v in (st["predicted"], st["measured"])]
    margin = 0.08 * (max(vals) - min(vals))
    ax_min, ax_max = min(vals) - margin, max(vals) + margin
    reads_max = max(p[3] for pts in series.values() for p in pts)

    for cat in arms:
        rows = []
        for lname, pred, meas, reads in series[cat]:
            # Marker area carries how much evidence the layer contributes; a
            # 60-cell layer's ratio is binomial noise, a 22k-cell layer's is not.
            rows.append([pred, meas, reads, 0.7 + 2.1 * (reads / reads_max) ** 0.5])
        # Numeric columns only: pgfplots' table reader parses every column it
        # loads, so a layer-name column would break the read. The layer order is
        # recorded in the README instead.
        write_dat(out / f"fig4a_identity_{cat}.dat",
                  ["predicted", "measured", "reads", "marksize"], rows)
        st = stats[cat]
        write_dat(out / f"fig4a_identity_{cat}_total.dat",
                  ["predicted", "measured"], [[st["predicted"], st["measured"]]])

    plots = []
    for i, cat in enumerate(arms):
        cm = color_macro(cat)
        mk = MARKS[i % len(MARKS)]
        plots.append(f"    %% ---- {cat}: one point per unprotected layer ----")
        # `scatter` is only here to get a per-point mark size; without
        # `use mapped color` pgfplots also maps the marker COLOUR through the
        # current colormap and the series hue is silently thrown away.
        plots.append(
            f"    \\addplot[only marks, mark={mk}, scatter, forget plot,\n"
            f"             scatter/use mapped color={{draw={cm}, fill={cm}, fill opacity=0.85}},\n"
            f"             visualization depends on={{\\thisrow{{marksize}} \\as \\perpointmarksize}},\n"
            f"             scatter/@pre marker code/.append style={{/tikz/mark size=\\perpointmarksize}}]\n"
            f"      table[x=predicted, y=measured] {{fig4a_identity_{cat}.dat}};"
        )
        # The scatter marker code also drives the legend image, which would draw
        # the key in the colormap's colour rather than the series'. Hence
        # forget plot above and an explicit key here.
        plots.append(f"    \\addlegendimage{{only marks, mark={mk}, mark size=1.8pt,"
                     f" draw={cm}, fill={cm}}}")
        plots.append(f"    \\addlegendentry{{{tex_escape(PRETTY.get(cat, cat))}}}")
        plots.append(f"    %% whole network, drawn hollow so it reads as the aggregate")
        plots.append(
            f"    \\addplot[only marks, mark={mk}, mark size=2.6pt, draw={cm}, line width=1.1pt,"
            f" fill=white, forget plot]"
            f" table[x=predicted, y=measured] {{fig4a_identity_{cat}_total.dat}};"
        )

    body = (FIG4A.replace("@@COLORS@@", "  " + color_defs(arms, colors).replace("\n", "\n  "))
            .replace("@@PLOTS@@", "\n".join(plots))
            .replace("@@MIN@@", f"{ax_min:.4g}").replace("@@MAX@@", f"{ax_max:.4g}")
            .replace("@@W@@", "7.0cm").replace("@@H@@", "7.0cm"))
    return write_figure(out, "fig4a_identity", body), stats


# --------------------------------------------------------------------------
def _packing_table(arms, packing) -> str:
    rows = ["| category | cells | blocks | mean block length |",
            "|---|---|---|---|"]
    for c in arms:
        cells, blocks = packing["cells"][c], packing["totals"][c]
        rows.append(f"| {PRETTY.get(c, c)} | {cells:,} | {blocks:,} |"
                    f" {cells / blocks:.3f} |")
    return "\n".join(rows)


def _wrap_layers(names: list[str], per_line: int = 3) -> str:
    rows = [names[i:i + per_line] for i in range(0, len(names), per_line)]
    return "\n".join("  ".join(f"{n:<22s}" for n in r).rstrip() for r in rows)


def write_readme(out: Path, bundle, arms, colors, lmax, kmax, stats, packing,
                 pair_name="", args_pair_y="share") -> Path:
    data = bundle["data"]
    layer_order = data[arms[0]]["structure"]["layer_order"]
    lines = [
        "# Block-length mechanism panels (pgfplots/TikZ)",
        "",
        "Generated by `scripts/plot_blocklen_tikz.py`. Stdlib only -- no matplotlib,",
        "no torch; it runs on the Mac mount.",
        "",
        "```bash",
        "python scripts/plot_blocklen_tikz.py --only " + " ".join(arms),
        "```",
        "",
        "| figure | body to `\\input` | data |",
        "|---|---|---|",
        "| block-length distribution, y = share (fig1a) |"
        " `fig1a_blocklen_distribution_body.tex` | `fig1a_blocklen_distribution.dat` |",
        "| block-length distribution, y = count (fig1a) |"
        " `fig1a_blocklen_counts_body.tex` | `fig1a_blocklen_counts.dat` |",
        "| alternating stretches (fig2a) | `fig2a_alternating_stretches_body.tex` |"
        " `fig2a_alternating_stretches.dat` |",
        "| transition-density identity (fig4a) | `fig4a_identity_body.tex` |"
        " `fig4a_identity_<category>{,_total}.dat` |",
        f"| **fig1a + fig2a side by side** | `{pair_name}_body.tex` |"
        f" `{pair_name}.dat` |",
        "",
        f"The pair is a `groupplots` 1x2 with `scale only axis`, so `\\PanelWidth` and",
        "`\\PanelHeight` size the axis BOX and the two panels stay exactly equal",
        "however wide their tick labels come out. Both lengths, the panel gap and",
        "the two titles are `\\def` knobs at the top of the body. Its wrapper loads",
        "`\\usepgfplotslibrary{groupplots}` -- a paper preamble needs that too.",
        f"It carries the **{args_pair_y}** y-axis on the left; `--pair-y` switches it.",
        "",
        "A series given two colours is drawn as ONE line twice: solid in the first",
        "tone, then dashed in the second on top, so the tones alternate along it.",
        "Both `\\addplot`s are `forget plot` and the legend key is built by hand, or",
        "pgfplots would show two entries for one series. `\\DashOn` / `\\DashOff` at",
        "the top of the body set the rhythm. fig4a is a scatter -- no line to",
        "alternate along -- so it uses the first tone only.",
        "",
        "Each body carries its own `\\definecolor` block, so re-colouring a series is",
        "one edit at the top of the file -- no regeneration. Figure size and the",
        "plotted range are `\\def` knobs at the top for the same reason.",
        "",
        "## fig1a: two y-axes",
        "",
        "Two bodies, each with its OWN `.dat` holding only the columns it plots, so",
        "a figure's `.tex` and `.dat` always share a name and copying one figure's",
        "files into a paper cannot leave its table behind. Both tables have the same",
        "columns -- `L`, one per series, `faircoin` -- so switching view is an",
        "`\\input` of the other body. They are NOT the same picture rescaled:",
        "",
        "| | share view | count view |",
        "|---|---|---|",
        "| denominator | each arm's OWN block count | none -- raw counts |",
        "| what is conserved | `sum(share) = 1` | `sum(L x count)` = cells, equal across arms |",
        "| compares | distribution shape | where the cells sit |",
        "",
        _packing_table(arms, packing),
        "",
        "Because the arms hold the **same number of cells** but a different number of",
        "blocks, the count view has a denominator they genuinely share and conserves",
        "mass: it shows cells moving out of short blocks into long ones. The share",
        "view normalises that deficit away -- and the deficit is the effect, since",
        "mean block length is just cells / blocks. On a log axis the difference looks",
        "small (a uniform shift of the smaller-block-count arm), but it moves where",
        "the curves cross, so the two views disagree about which arm holds more",
        "blocks at small L.",
        "",
        "The count view's dashed reference is `2^-L` scaled by the **baseline's**",
        "block count: the arms have no shared total, and the baseline is the",
        "random-sign arm, so the line reads as \"what the baseline would hold\".",
        "",
        "## Series",
        "",
        "| category | colour | `\\definecolor` macro | drawn |",
        "|---|---|---|---|",
    ]
    for c in arms:
        hx = hexes(colors, c)
        swatch = " + ".join(f"`{h.upper()}`" for h in hx)
        macros = " + ".join(f"`{color_macro(c)}{'' if j == 0 else 'Alt'}`"
                            for j in range(len(hx)))
        how = "solid, with the second tone dashed over it" if len(hx) > 1 else "solid"
        lines.append(f"| {PRETTY.get(c, c)} (`{c}`) | {swatch} | {macros} | {how} |")
    lines += [
        "",
        "## What backs the numbers",
        "",
        f"- Source tree: `{bundle['rt_tag']}` slice of"
        " `runs/paper-runs/paper-sw_resnet18_imagenette`",
        f"- Seeds pooled per series: {', '.join(sorted(data[arms[0]]['seeds']))}",
        "- Restricted to the 19 **unprotected** conv layers: the protected ones"
        " (`conv1`, `linear`) never see a fault.",
        f"- fig1a plots L = 1..{lmax}, fig2a k = 2..{kmax} -- past those the histogram"
        " holds fewer than 5 stretches and a point is one lucky racetrack.",
        "",
        "## fig4a reads as a test, not a fit",
        "",
        "x is computed from the stored weights alone"
        " (`sign_transitions / (bits - n_racetracks)`, the share of adjacent cell",
        "pairs holding opposite signs). y is counted by the fault simulator"
        " (`bitflips / wrong_bits_read` at iteration 1). Nothing is fitted, so the",
        "dashed `y = x` is a prediction the points either land on or they do not:",
        "",
        "| series | predicted | measured | error |",
        "|---|---|---|---|",
    ]
    for c in arms:
        st = stats[c]
        err = 100 * (st["measured"] - st["predicted"]) / st["predicted"]
        lines.append(f"| {PRETTY.get(c, c)} | {st['predicted']:.5f} |"
                     f" {st['measured']:.5f} | {err:+.2f}% |")
    lines += [
        "",
        "Marker area carries `wrong_bits_read` for that layer: the scatter around the",
        "line is concentrated in the smallest layers, where only a few dozen cells",
        "were misread and the ratio is binomial noise rather than model error.",
        "",
        "The `.dat` rows are in model order, so row *n* is the *n*-th layer below.",
        "Layer names are kept out of the table: pgfplots parses every column it",
        "loads, and a string column breaks the read.",
        "",
        "```",
        _wrap_layers(layer_order),
        "```",
        "",
        "## Verified",
        "",
        "All three wrappers compile clean with `tectonic -X compile <name>.tex`",
        "(pgfplots 1.18). Two things that bit during the build and are worth not",
        "re-introducing:",
        "",
        "- `scatter` (used in fig4a only to get a per-point mark size) also maps the",
        "  marker COLOUR through the current colormap. Without",
        "  `scatter/use mapped color` the series hue is silently replaced by a",
        "  rainbow, and the legend key goes black. Hence the explicit",
        "  `\\addlegendimage` beside a `forget plot` scatter.",
        "- The series colours pass a colourblind check as a pair"
        " (CVD dE 16.2 protan, 30.3 normal-vision), but `EDA100` sits below 3:1",
        "  contrast on white, so it needs its legend entry or a direct label --",
        "  never colour alone. Both figures carry a legend, and the two series also",
        "  differ in marker shape so they survive greyscale printing.",
        "",
        "The identity is quoted at `rt_error = 1e-05`. It degrades at higher dose"
        " (up to +5.5% for the endlen arm at 1e-4) because offsets beyond one cell",
        "accumulate before the first measurement -- see `../blocklen/README.md`.",
        "",
    ]
    path = out / "README.md"
    path.write_text("\n".join(lines))
    return path


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--runs", type=Path, default=DEFAULT_RUNS)
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT)
    ap.add_argument("--rt-error", default="1e-05")
    ap.add_argument("--only", nargs="+", metavar="CATEGORY", default=DEFAULT_ARMS,
                    help="categories to plot (default: %(default)s)")
    ap.add_argument("--color", action="append", default=[], metavar="CAT=HEX",
                    help="override a series colour: HEX, or HEX/HEX for a line "
                         "that alternates between two tones, e.g. "
                         "cat5_regularizer=EB6834/EDA100")
    ap.add_argument("--pair-y", choices=["share", "count"], default="count",
                    help="which fig1a y-axis the side-by-side figure uses. "
                         "Default `count`: both arms store the same number of "
                         "cells, so counts share a denominator and the panel "
                         "conserves mass. (default: %(default)s)")
    ap.add_argument("--fig1a-y", nargs="+", choices=["share", "count"],
                    default=["share", "count"], metavar="VIEW",
                    help="y-axis for fig1a: share of all blocks, number of blocks, "
                         "or both (default). Both read the same .dat.")
    args = ap.parse_args()

    colors = dict(DEFAULT_COLORS)
    for spec in args.color:
        cat, _, hexval = spec.partition("=")
        parts = hexval.split("/")
        if not (1 <= len(parts) <= 2
                and all(re.fullmatch(r"[0-9A-Fa-f]{6}", h) for h in parts)):
            raise SystemExit(f"--color {spec}: need HEX or HEX/HEX (6-digit), "
                             f"got {hexval!r}")
        colors[cat] = parts[0] if len(parts) == 1 else tuple(parts)

    bundle = collect(args.runs, args.rt_error, only=args.only)
    arms = structure_arms(bundle)
    dropped = [c for c in bundle["categories"] if c not in arms]
    missing = [c for c in arms if c not in colors]
    if missing:
        raise SystemExit("no colour for " + ", ".join(missing) + " -- pass --color")

    args.out.mkdir(parents=True, exist_ok=True)
    written = []
    f1, lmax, packing = build_fig1a(args.out, bundle, arms, colors, args.fig1a_y)
    f2, kmax = build_fig2a(args.out, bundle, arms, colors)
    f4, stats = build_fig4a(args.out, bundle, arms, colors)
    fp, pair_name = build_pair(args.out, bundle, arms, colors, args.pair_y)
    written += f1 + f2 + f4 + fp
    written.append(write_readme(args.out, bundle, arms, colors, lmax, kmax, stats,
                                packing, pair_name, args.pair_y))

    print("series: " + ", ".join(
        f"{c} ({' + '.join(h.upper() for h in hexes(colors, c))}"
        + (", two-tone)" if two_tone(colors, c) else ")") for c in arms))
    if dropped:
        print(f"  folded out (structure identical to another arm): {', '.join(dropped)}")
    for c in arms:
        st = stats[c]
        err = 100 * (st["measured"] - st["predicted"]) / st["predicted"]
        print(f"  {c:20s} predicted={st['predicted']:.5f} measured={st['measured']:.5f}"
              f" ({err:+.2f}%)  layers={st['layers']}")
    print(f"fig1a L=1..{lmax}   fig2a k=2..{kmax}")
    for p in written:
        print(f"wrote {p}")
    for p in sorted(args.out.glob("*.dat")):
        print(f"wrote {p}")


if __name__ == "__main__":
    main()
